---
api:
  dashboard: true
providers:
  file:
    filename: /etc/traefik/dynamic.yml
  docker:
    network: local
    defaultRule: "Host(`{{ .Name }}.test`)"
    exposedByDefault: false
entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"
log:
  level: info
global:
  checkNewVersion: true
  sendAnonymousUsage: false