version: '3'

services:
  db:
    image: 'mariadb:10.2'
    ports:
      - '3306:3306'
    volumes:
      - /var/lib/mysql
      - ./dev/mysql/custom-config.cnf:/etc/mysql/conf.d/custom-config.cnf
      - ./dev/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    restart: unless-stopped
    hostname: db.magento2.docker
    networks:
     - magento
    env_file:
      - ./global.env
  fpm:
    image: 'sashas777/magento-php:7.2-fpm'
    hostname: fpm.magento2.docker
    ports:
      - 9000
    depends_on:
      - db
      - cron
      - mailhog
#    volumes_from:
#      - appdata
    env_file:
      - ./global.env
    restart: unless-stopped
    networks:
     - magento
    volumes:
      - ./src:/var/www/magento:rw
#      - vendor:/var/www/magento/vendor
#      - pub:/var/www/magento/pub
#      - var:/var/www/magento/var
#      - generated:/var/www/magento/generated
#      - etc:/var/www/magento/etc
  web:
    image: 'sashas777/magento-nginx:latest'
    ports:
      - '443:443'
    depends_on:
      - fpm
      - db
 #   volumes_from:
 #     - appdata
    env_file:
      - ./global.env
    restart: unless-stopped
    networks:
     - magento
    volumes:
      - ./src:/var/www/magento:rw
      - ./dev/ssl:/etc/nginx/ssl:ro
      - ./dev/nginx/mapping.conf:/etc/nginx/conf.d/a-mapping.conf:rw
#      - vendor:/var/www/magento/vendor
#      - pub:/var/www/magento/pub
#      - var:/var/www/magento/var
#      - generated:/var/www/magento/generated
#      - etc:/var/www/magento/etc
  cli:
    image: 'sashas777/magento-php:7.2-cli'
    hostname: cli.magento2.docker
    restart: unless-stopped
    depends_on:
      - db
      - mailhog
    volumes:
      - /.dev/composer-cache:/root/.composer/cache:rw
      - ./src:/var/www/magento:rw
#      - vendor:/var/www/magento/vendor
#      - pub:/var/www/magento/pub
#      - var:/var/www/magento/var
#      - generated:/var/www/magento/generated
#      - etc:/var/www/magento/etc
#
#    volumes_from:
#      - appdata
    env_file:
      - ./global.env
    networks:
     - magento
  cron:
    image: 'sashas777/magento-php:7.2-cli'
    hostname: cron.magento2.docker
    depends_on:
      - db
      - cli
      - mailhog
    restart: unless-stopped
    volumes:
      - ./src:/var/www/magento:rw
#      - vendor:/var/www/magento/vendor
#      - pub:/var/www/magento/pub
#      - var:/var/www/magento/var
#      - generated:/var/www/magento/generated
#      - etc:/var/www/magento/etc
#    volumes_from:
#      - appdata
    env_file:
      - ./global.env
    command: run-cron
    networks:
     - magento
  mailhog:
    image: mailhog/mailhog
    networks:
     - magento
    ports:
      - '8025:8025'
#  appdata:
#    image: tianon/true
#    volumes:
#      - './src/mnt:/mnt'
#      - /var/www/magento/vendor
#      - /var/www/magento/generated
#      - /var/www/magento/pub
#      - /var/www/magento/var
#      - /var/www/magento/app/etc
#  data:
#    image: tianon/true
#    networks:
#      - magento
#    volumes:
#      - vendor:/var/www/magento/vendor
#      - pub:/var/www/magento/pub
#      - var:/var/www/magento/var
#      - generated:/var/www/magento/generated
#      - etc:/var/www/magento/etc
networks:
  magento:
   external:
    name: magento
