version: '3.8'

services:
  db:
    image: 'mariadb:10.4'
    ports:
      - '3306:3306'
    command: >
      bash -c "
      chmod 644 /etc/mysql/conf.d/*.cnf
      && docker-entrypoint.sh mysqld
      "
    volumes:
      - ./dev/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ~/mysql:/var/lib/mysql
      - ./dev/mysql/custom-config.cnf:/etc/mysql/conf.d/custom-config.cnf
    restart: unless-stopped
    hostname: db.magento2.docker
    env_file:
      - ./global.env
  fpm:
    image: 'sashas777/magento-php:7.4-fpm'
    hostname: fpm.magento2.docker
    ports:
      - 9000
    depends_on:
      - db
    env_file:
      - ./global.env
    restart: unless-stopped
    volumes:
      - ./src:/var/www/magento:rw
  web:
    image: 'sashas777/magento-nginx:latest'
    depends_on:
      - fpm
      - db
    env_file:
      - ./global.env
    restart: unless-stopped
    volumes:
      - ./src:/var/www/magento:rw
    labels:
      - traefik.enable=true
      - traefik.http.routers.web.tls=true
      - traefik.http.routers.web.rule=Host(`${WEBSITE_DOMAIN}`)
      - traefik.http.services.web.loadbalancer.server.port=8080
  cli:
    image: 'sashas777/magento-php:7.4-cli'
    hostname: cli.magento2.docker
    restart: unless-stopped
    command: run-cron
    depends_on:
      - db
      - elasticsearch
    volumes:
      - ~/.cache/composer:/root/.cache/composer:rw
      - ./src:/var/www/magento:rw
    env_file:
      - ./global.env
  elasticsearch:
    image: 'sashas777/magento-elasticsearch:7.9.3'
    hostname: elasticsearch.magento2.docker
    restart: unless-stopped
    environment:
      ES_NETWORK_HOST: 'localhost'
      ES_JAVA_OPTS: '-Xms1024m -Xmx1024m'
    ports:
      - "9200:9200"
  rabbitmq:
    hostname: rabbitmq.magento2.docker
    image: rabbitmq:3.8-management
    ports:
      - "5672"
    labels:
      - traefik.enable=true
      - traefik.http.routers.rabbitmq.tls=true
      - traefik.http.routers.rabbitmq.rule=Host(`rabbitmq.${WEBSITE_DOMAIN}`)
      - traefik.http.services.rabbitmq.loadbalancer.server.port=15672
    volumes:
      - ./dev/rabbitmq:/var/lib/rabbitmq
  redis:
    hostname: redis.magento2.docker
    image: 'sashas777/magento-redis:5.0'
    ports:
      - 6379
    volumes:
      - ./dev/redis:/data

networks:
  default:
    name: local